server:
  port: 8762

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredServices: "*"
  routes:
    organization-service:
      path: /organization/**
      service-id: organization-service
    authentication-service:
      path: /authentication-service/**
      service-id: authentication-service

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000